
name: Ayala - Manually

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v3 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v3
        with:
          ref: main
          python-version: '3.x' # install the python version needed
          
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
          installer-parallel: true
      
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
          
      - name: execute py script
        env: 
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET_KEY: ${{ secrets.API_SECRET_KEY }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
          HEROKU_URI: ${{ secrets.HEROKU_URI }}
          SUPABASE_URI: ${{ secrets.SUPABASE_URI }}
        run: poetry run python src/tweets_search.py
